
#
# based on the book:
#  The Algorithmic Beauty of Plants
#
# by:
#  Przemyslaw Prusinkiewicz
#  Aristid Lindenmayer
#

#  Example fom page 48
#  equation 1.9: see page 49, figure 1.39
#

#
#  This seems to validate the left hand context.
#


lsystem : context_colors_agop_pg48


	derivations : 15

	define : theta : rad(85)
	define : R : 1.456

	branchsymbols : []
	ignore : +-
	

	axiom : A(1)


	production :R(x): A(s) :*:*: G(s)[+A(s/R)][-A(s/R)]
	production :G(x): A(s) :*:*: B(s)[+A(s/R)][-A(s/R)]
	production :B(x): A(s) :*:*: R(s)[+A(s/R)][-A(s/R)]
	production :*: A(s) :*:*: R(s)[+A(s/R)][-A(s/R)]


	group : R(d) : C(255,0,0)F(d)
	group : G(d) : C(0,255,0)F(d)
	group : B(d) : C(0,0,255)F(d)


	alias : A(a) : null
	alias : F(a) : MoveOnAxisWithLine : 1 : a
	alias : + : RotateOnAxis : 2 : theta 
	alias : - : RotateOnAxis : 2 : -theta
	alias : [ : PushStack
	alias : ] : PopStack




	alias : C(r,g,b) : SetColor : r : g : b
